### PR TITLE
Project - Georgii Ustinov [NUP]

### PR DESCRIPTION
**Pull request by Hardes1**
I completed "Wordle-solver" project (for 60 points now)

### CODE REVIEW

**Comment by Hardes1** [comment]
Please, see README.MD

**Comment by kajigor** [comment]
Please request a code review in the repo with the solution.

**Comment by Hardes1** [comment]
Please,  accept the invitation to my repository (Hardes1/wordle-solver) and watch [this PR](https://github.com/Hardes1/wordle-solver/pull/1) for code review

**Comment by kajigor** [comment]
Very well done. I've left some comments in the PR, but you don't need to fix them.  
The tasks done: 
* minimum
* computing the best word 

Total 80 points

**Pull request closed without merging**
