### PR TITLE
HW08 Georgii Ustinov [NUP]

### PR DESCRIPTION
**Pull request by Hardes1**
I probably add to few tests :(

### CODE REVIEW

**Comment by kajigor** [comment]
One thing you need to keep in mind when implementing generators is to make sure that they generate relevant values often. For example, if you want to test simplification, then it's important to generate expressions that can actually be simplified.

I augmented your test with some debug prints for whenever the expression was changed: 

```
import Debug.Trace

simplifyCompositionEval :: Property
simplifyCompositionEval = property $ do
  expr <- forAll $ genExpr 100
  bindings <- forAll $ genBindnigsToVariables 100
  let simplified = simplify expr
  (if simplified /= expr then trace "\nDifferent simplified and expr!" else id) $
    assert $ evalExpr expr bindings == evalExpr simplified bindings
``` 

I ran this test 10 times. In about half of them, there was not a single expression changed by simplification for 100 runs. Only once it notified me 3 times. This means that only 1% of your tests actually test simplification. How likely is it for the test to catch a bug in this case? 

Could you tweak your generator so that it's more useful? 

You can also try to come up with some additional properties. For example, you can test that the evaluator follows the properties of arithmetic operations (`1 * x == x`, `1 / x * x == x` and so forth)

**Comment by Hardes1** [comment]
I agree, that my generator is quite weak and `simplify` indeed simplify the expression very rare. However, if we suppose that we use our function in reality, there are only few cases when it may simplify the expression. I can check some corner cases of the simplification, by providing special generators, but in this case I don't understand what is difference between my test and unit tests.

**Comment by Hardes1** [comment]
Well, I realized, that I forgot to push tests related to the eval😔😔😔. Also, I restricted the number for constants for simplify tests, so now we have ~10/100 tests where simplify actually do something

**Comment by kajigor** [comment]
I would argue that the fact that the simplication is not applicable in reality depends on what the reality is. You don't know, how your library will be used. It is possible that someone will write many long expressions with multiple simplification points. 

Besides that, when you're testing a function, you must ensure that the function is actually being tested, otherwise what's the point? 

You can achieve this by making your generator produce lower numbers more often: use other `Range`'s than `constant`, or generate binOps between equal expressions in, say, 10% of the times. 

This is better than unit tests, because they are still random and there are more of them. 

Try fixing it.

**Comment by Hardes1** [comment]
Sorry, should (and can) I do anything else here? I guess, I got a mark in the table, but the PR is not closed.

**Comment by kajigor** [comment]
> You can achieve this by making your generator produce lower numbers more often: use other `Range`'s than `constant`, or generate binOps between equal expressions in, say, 10% of the times.
> 
> This is better than unit tests, because they are still random and there are more of them.
> 
> Try fixing it.

**Comment by kajigor** [comment]
1 ok

**Pull request closed without merging**
