### PR TITLE
Exam: Egor Kukoverov

### PR DESCRIPTION
**Pull request by ubuntuegor**

### CODE REVIEW

**Comment by ubuntuegor** [comment]
my markdown reader didn't display roman numerals so I accidentally did all variants 😅  
image

**Comment by kajigor** [comment]
1 ok
2 ok 
3 ok 
4 - 

5 Ok, Even though I had a different notion of numbers base n in mind, in which `BInteger 2 11 == BInteger 10 3`.  
6 ok. what's up with the infinite lists? 
7 -
8 -

**Comment by kajigor** [comment]
so, what'll happen if you run rotate on an infinite list with different n?

**Comment by ubuntuegor** [comment]
6. Added a test case for an infinite list. It works only when n >= 0, because for negative rotations we need to know the length of the list and that will never compute for infinite lists

**Comment by kajigor** [comment]
ok

**Pull request closed without merging**
